### ISSUE TITLE
Data/Metadata Cleanup

### ISSUE THREAD

**Issue by lweakly** [CDRH/family_letters#17]
- [x] Format -- Capitalize "manuscript"; change remaining (front) and (back) to (recto) and (verso) (Made new issue for manuscript #53 )
- [x] People -- figure out what "No label" means and fix; check for duplicate people, for example  #55
- [x] Guadalupe Flemate and Guadalupe Flemate Medrano #55
- [x] Creator -- same as people #55
- [x] Language Code -- ji change to en (fixed, it was only in one file)
- [x] Subcategory -- Letters in UC, while other are lc -- make consistent see #52
- [x] Places -- not pulled Jess addressed below, created new issue #54
- [x] Subcategory: Photos are not represented (this is done, but more regularization needed see #52)
- [x] in some dates, if the date is between 1-9, it has a leading 0, in other places there is no leading 0 -- make consistent  see #56
